path='/run/media/webrain/Data1/ZihaoZheng/Data/ADNI/MCI/DTI/*.bed*';
files=dir(path);
files(1:2)=[];
T1_path='/usr/local/fsl/data/standard/MNI152_T1_2mm_brain.nii.gz';
% mask_path='/run/media/webrain/Data1/ZihaoZheng/Data/ADNI/MCI/Schaefer2018_200Parcels_7Networks_order_FSLMNI152_2mm.nii';

mask_path='/run/media/webrain/Data1/ZihaoZheng/Data/ADNI/MCI/raal.nii';
f=filesep;

for i=1:length(files)
    try

    subname=files(i).name(1:end-9);
    in_path=['/run/media/webrain/Data1/ZihaoZheng/Data/ADNI/MCI/DTI/',subname];
    FA_files=dir([in_path,'/*_FA*']);
    
    system(['flirt -in ' T1_path ' -ref ' FA_files.folder f FA_files.name ' -out ' ...
    in_path f 'my_linear' ' -omat ' in_path f 'my_linear.mat' ' -bins 256 -cost corratio -searchrx -90 90'...
    ' -searchry -90 90 -searchrz -90 90 -dof 12  -interp nearestneighbour ']);
    system(['flirt -in ' mask_path ' -ref ' FA_files.folder f FA_files.name ' -out ' ...
        in_path f 'aal_to_DTI.nii.gz' ' -applyxfm -init ' in_path f 'my_linear.mat' '   -interp nearestneighbour ']);
    system(['gunzip ' in_path f 'aal_to_DTI.nii.gz']);
    
    nodif_mask_fileName=[files(i).folder f files(i).name f 'nodif_brain_mask.nii.gz'];
    samples_basefileName=[files(i).folder f files(i).name f 'merged'];
   
    roi_list=[in_path f 'aal_to_DTI.nii'];
    output_dir=[in_path f 'SC_AAL'];
    mkdir(output_dir);
    
    
    mkdir([in_path,f,'ROIs_AAL']);
    
    [mask,Header]=y_Read(roi_list);
    index=unique(mask(:));
    for j=1:length(index)-1
        temp=mask;
        temp(temp~=j)=0;
        temp(temp~=0)=1;
        
        outname = sprintf('ROI_%03d.nii', j);
        y_Write(temp,Header,[in_path f 'ROIs_AAL' f outname])


    end
    
    %=== 设置 ROI 文件所在的目录 ===
    roi_dir = [in_path f 'ROIs_AAL'];

    %=== 获取所有 ROI 文件（假设名字是 ROI_001.nii.gz, ROI_002.nii.gz ...）===
    roi_files = dir(fullfile(roi_dir, 'ROI_*.nii'));

    %=== 输出的列表文件路径 ===
    list_file = fullfile(in_path, 'roi_list.txt');

    %=== 打开文件，写入 ROI 文件的绝对路径 ===
    fid = fopen(list_file, 'w');
    for j = 1:length(roi_files)
        % 拼接绝对路径
        roi_path = fullfile(roi_files(j).folder, roi_files(j).name);
        fprintf(fid, '%s\n', roi_path);
    end
    fclose(fid);
    
    
%     
%  probtrack_cmd=cat(2 ,'probtrackx2 -x ',list_file,...
%                        ' -l --onewaycondition -c 0.2 -S 2000 --steplength=0.5 -P 5000 --fibthresh=0.01 --distthresh=0.0 --sampvox=0.0 --forcedir --opd',...
%                        ' -s ', samples_basefileName,...
%                        ' -m  ',nodif_mask_fileName,...
%                        ' --network ',...
%                        ' --dir=', output_dir,...
%                        ' --waycond=AND --pd') ; 
%                    tic
%                    
%                    system(probtrack_cmd);
%                    toc
%   
                   
%   Label_seed_fileName='/run/media/webrain/Data1/ZihaoZheng/Data/ADNI/MCI/DTI/003_S_0908_T2_2017-10-20_13_55_34.0/ROIs/ROI_001.nii' ;               
%   targets_txt_fileName=  '/run/media/webrain/Data1/ZihaoZheng/Data/ADNI/MCI/DTI/003_S_0908_T2_2017-10-20_13_55_34.0/ROIs/ROI_002.nii' ;                   
%   probtrack_cmd=cat(2 ,'probtrackx2 -x ',Label_seed_fileName,...
%                        ' -l --onewaycondition -c 0.2 -S 2000 --steplength=0.5 -P 5000 --fibthresh=0.01 --distthresh=0.0 --sampvox=0.0 --forcedir --opd',...
%                        ' -s ', samples_basefileName,...
%                        ' -m  ',nodif_mask_fileName,...
%                        ' --dir=', output_dir,...
%                        ' --targetmasks=',targets_txt_fileName,...
%                        ' --waypoints=',targets_txt_fileName,...
%                        ' --waycond=AND --pd') ;    
%                    
%     probtrack_cmd=cat(2, 'probtrackx --mode=seedmask',...
%                          ' -l --opd -c 0.2 -S 1000 --steplength=0.5 -P 5000',...
%                          ' -x ', Label_seed_fileName,...
%                          ' --forcedir --pd --s2tastext',...
%                          ' --targetmasks=', targets_txt_fileName,...
%                          ' -s ', samples_basefileName,... 
%                          ' -m ', nodif_mask_fileName,...                       
%                          ' --dir=', output_dir);               
%                    
%           probtrack_cmd=cat(2, 'probtrackx --mode=seedmask',...
%                          ' -l --opd -c 0.2 -S 1000 --steplength=0.5 -P 5000',...
%                          ' --stop=', targets_txt_fileName,...
%                          ' -x ', Label_seed_fileName,...
%                          ' --forcedir --pd --s2tastext',...
%                          ' --targetmasks=', targets_txt_fileName,...
%                          ' -s ', samples_basefileName,... 
%                          ' -m ', nodif_mask_fileName,...                       
%                          ' --dir=', output_dir);     
%                      
%                      A
%                    probtrack_cmd=cat(2, 'probtrackx2 ',...
%                          ' -l --opd -c 0.2 -S 1000 --steplength=0.5 -P 5000',...
%                          ' -x ', Label_seed_fileName,...
%                          ' --forcedir --pd --s2tastext',...
%                          ' --targetmasks=', list_file,...                       
%                          ' -s ', samples_basefileName,... 
%                          ' -m ', nodif_mask_fileName,...                       
%                          ' --dir=', output_dir);
%                      
%               probtrack_cmd=cat(2, 'probtrackx2 ',...
%                          ' -l --opd -c 0.2 -S 1000 --steplength=0.5 -P 5000',...
%                          ' --seed=', list_file,...
%                          ' --forcedir --pd --s2tastext --os2t',...
%                          ' --targetmasks=', list_file,...
%                          ' -s ', samples_basefileName,... 
%                          ' -m ', nodif_mask_fileName,... 
%                          ' --network',...
%                          ' --dir=', roi_dir);
%                      
%                    probtrack_cmd=cat(2, 'probtrackx2 ',...
%                          ' -l --opd -c 0.2 -S 1000 --steplength=0.5 -P 5000',...
%                          ' -x ', Label_seed_fileName,...
%                          ' --forcedir --pd --s2tastext',...
%                          ' --targetmasks=', targets_txt_fileName,...                       
%                          ' -s ', samples_basefileName,... 
%                          ' -m ', nodif_mask_fileName,...                       
%                          ' --dir=', output_dir);
tic    
if length(roi_files)==116
        parfor roi=1:116
            Label_seed_fileName=[roi_files(roi).folder f roi_files(roi).name];
            outname = sprintf('ROI_%03d', roi);
            output_dir_track=[in_path f 'SC_AAL' f outname];
            mkdir(output_dir_track)
              probtrack_cmd=cat(2, 'probtrackx2 ',...
                         ' -l --onewaycondition -c 0.2 -S 1000 --steplength=0.5 -P 5000',...
                         ' -x ', Label_seed_fileName,...
                         ' --forcedir --opd --os2t --s2tastext',...
                         ' --targetmasks=', list_file,...                       
                         ' -s ', samples_basefileName,... 
                         ' -m ', nodif_mask_fileName,...                       
                         ' --dir=', output_dir_track); 
 
                   system(probtrack_cmd);
        end
end
    toc
    catch
        continue;
    end
                   

                     

    
end

